### ISSUE TITLE
Do we want to have a blog?

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#102]
@garrying brought up that we have had moments where a long-form content would be lovely on the site:

- field testing
- benchmark results
- maybe even recaps from big events (makerfestival, attending HOPE)

**Comment by benhylau** [comment]
Definitely would like long-form content. Everything is hiding in documents repo atm

**Comment by benhylau** [comment]
Post for Radical Networks talk by @garrying and @uditvira too :)

**Comment by dcwalk** [comment]
My unreasonable dislike of blogs appears to have been holding us back this whole time ⚫️ 

I'm a no-block 👊 on the blog, with my main concern that an unmaintained blog looks worse than none at all.

**Comment by benhylau** [comment]
>long-form content

Don't have to be a blog!

**Comment by darkdrgn2k** [comment]
+1 on dcwalks comment

From experience a blog are fine untill they are no longer posted to.... To many blogs exist with the last post have not been updates  in years and make the site look like a ghost town!

With the collaboration angle being to use git, perhaps just a way to nicely organize and link to the git content from the site would work better?

**Comment by benhylau** [comment]
Since everyone seems to prefer no blog, and we have already addressed all items in the original issue with https://github.com/tomeshnet/documents/tree/master/technical and https://tomesh.net/timeline/ I am closing this issue.
