### ISSUE TITLE
Update website to reflect outcomes of State of Our Networks

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#121]
I think there are a couple urgent things:

-  Indicate the event is passed on event page, similar to #100 (can this be handled with callouts? alerts? similar to bootstrap) (to be handled separately)
- [x] **Small write up!!**
- [x] update event with final bio
- [x] update timeline to include event
- [x] deal with media coming out of event (below)
  - [ ] CC 4.0 BY-NC-SA licensed on our accts

Pictures
https://www.flickr.com/photos/glennmcknight/albums/72157675518024343

Videos
First presentation: https://www.youtube.com/watch?v=f9utcVcAVCQ
Second presentation: https://www.youtube.com/watch?v=O1idjfeB3EM
Third: ?
Fourth: ?

Audio
https://soundcloud.com/gmcknight/mesh-toronto-panel-discussion

**Comment by benhylau** [comment]
Can we serve the video over IPFS?

**Comment by benhylau** [comment]
Glenn posted a bunch of other recordings: https://www.youtube.com/user/gcmcknight/videos?shelf_id=4&view=0&sort=dd

Some of them are of the same talk, let's clarify which ones we should host / archive? @JoshuaOpolko is the contact?

**Comment by dcwalk** [comment]
He sent the link to me, I just pinged again RE: missing soundcloud file and status of the videos. the problem with video know is after the first 2 presentations they are cut off snippets :(

**Comment by dcwalk** [comment]
Video and photos are okay to be released as CC 4.0, I'm proposing BY-NC-SA because these are peoples' likenesses (https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by benhylau** [comment]
Audio files are okay

**Comment by dcwalk** [comment]
@JoshuaOpolko You mentioned working on the A/V is there an update on those?

**Comment by dcwalk** [comment]
Addressing in https://github.com/tomeshnet/tomesh.net/pull/127

**Comment by dcwalk** [comment]
Small write up to live in docs repo until we get that feature added to the website.

**Comment by dcwalk** [comment]
RE: media-- I do not believe will have access to video that is usable for all of the speakers so propose we go ahead with out it. We have photos (in addition to those I've taken), I followed up with Glenn RE: audio as it would be a shame to also not have that.

If I don't hear back I'm proposing we drop it and chalk it up to a lesson learned for next event.

**Comment by benhylau** [comment]
Agree on dropping video. Should we host the image and audio files? Git, IPFS, ...

**Comment by dcwalk** [comment]
Haven't heard anything further about media so closing this/dropping this. @benhylau -- please take a stab a throwing any up on IPFS and maybe into our docs repo as you see fit?
