### ISSUE TITLE
Replace Font Awesome icons with SVGs

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#134]
A few points on moving towards SVGs: https://css-tricks.com/icon-fonts-vs-svg/

**Comment by dcwalk** [comment]
Cool-- my sense is that font awesome/fonts are pretty quick and dirty. The only experience I have with SVGs involves using some sort of build tools/task runner... which seems like the biggest complexity drawback. 

I've never heard of IcoMoon, which is mentioned in the article. How would you see the creating/generating workflow operating?

**Comment by garrying** [comment]
I've only used IcoMoon for generating icon fonts and haven't tried their svg generator.

Thinking there is a way of doing it without adding too much overhead, or external external dependancies, in Jekyll. One idea I'm curious to try is creating an include that would embed an icon with a param to specify an svg file.
