### ISSUE TITLE
Listing of all Toronto Mesh projects

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#137]
I think the project information and possibly some way to communicate the skill sets each one needs would be beneficial to have on the website. It is currently still a challenge for new people joining the tomesh to discover projects, and eventually finding something that matches with their interests and skills. Here is a pad we have thrown together as an emergency answer to "what is the status and how can I help?"

https://cryptpad.fr/code/#/1/view/5WwseaPrSrnmkDuNVcBiTw/zqwAlbdxT0t9BHfSEFunbT7kB9Se5oAW-sHix6kK4Qo

**Comment by garrying** [comment]
A list of projects would be helpful, but I have concerns about posting the entire list on the site and I wonder if we could bring some focus to projects that have momentum (at least as an entry point to other projects). In its current, cryptpad, state there is little describing each project which makes me think that this could take a bit of effort to put together and maintain its relevancy over time. Imagining a scenario where one is asking "what is the status and how can I help?" only to find dated status and requests.

**Comment by benhylau** [comment]
I am happy to write the content for the projects I am involved in. We can start with 6 most active projects, and link visitors to wekan for more. So this is more like a list of Featured Projects than a full listing.

**Comment by dcwalk** [comment]
I agree with @garrying RE: focus and momentum being more important than a comprehensive listing. I'm also wondering if we might want to think through how and why people are getting interested and connect that to where we put the information.

For instance -- I'm not sure the Wekan is getting much use, but we have much (all?) of this information there. Is there a way to connect better the places we already have information?

**Comment by benhylau** [comment]
I think Wekan is okay to keep track of stuff for people already familiar with the project. For someone new, it's very hard to navigate that space. Things are presented without emphasis on most active / critical projects.

**Comment by dasanchez** [comment]
The Projects Page was added through PR #228.
