### ISSUE TITLE
Add a license to our website and repo

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#14]
We should have a license indicated on our website before we start putting much more content up there. 
Something like `(C) Toronto Mesh. Content and documentation licensed under XXX. 2016 Code licensed under XXXX."  They should be added to our repository as well!

My preference for **content** would be Creative Commons 4.0 ([CC BY-SA 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/) for text/content.

For **code** however I am unsure, looks like all of the site stuff (Jekyll, Skeleton, Font Awesome) are MIT license, I've tended toward stronger GPL variants but don't have a strong preference.

Thoughts?

(actually, should say I've be up for an anti-copyright attribution too :sparkles: but don't know how to do that for code)

**Comment by benhylau** [comment]
For code, I generally prefer GPLv3, and use Apache/MIT on a case-by-case basis if there is good reason for it. I feel GPL is appropriate for most of what we do here.

For content I am okay with CC 4.0.

**Comment by garrying** [comment]
^ ignore my goof up'd reference

**Comment by garrying** [comment]
Closing with #33 merge.
