### ISSUE TITLE
Do we want secondary navigation for About, Get involved?

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#152]
Do we want to add in secondary nav in order to:

About:
- add timeline under about
- add code of conduct to top nav
- make meeting notes and governance docs more present on site

Get Involved:
- surfacing current projects under get involved (like hardware! prototype node!)

**Comment by darkdrgn2k** [comment]
If you do want to add submenus, here is some CSS i wipped up to get you started

This will add the ability to easily add css hover menus into the current menu of the site
https://github.com/tomeshnet/tomesh.net/compare/master...darkdrgn2k:DrowDown-Menu

Example adds sub menus to Contact menu items but same concept can be used for any other item

**Comment by Shrinks99** [comment]
## Proposed Menu Structure

- About
  - Timeline
  - Code of Conduct
- Events
- Get Involved
  - Build a Node*
  - Join the Network*
- Map*
- Contact
  - Twitter
  - Email
  - Riot
  - Github

Contact could also possibly be removed.

&ast; Indicates future pages

**Comment by darkdrgn2k** [comment]
https://matrix.tomesh.net/_matrix/media/v1/download/tomesh.net/HSafbhgeajeIDNgFWfnySNCg

**Comment by darkdrgn2k** [comment]
see #169 for new Build A Node page

**Comment by garrying** [comment]
Closed with #172
