### ISSUE TITLE
Update Global Navigation

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#153]
@garrying, @darkdrgn2k, @Shrinks99 and I discussed how the the global nav needs to be updated to account for the map, but also wanted to revisit it more generally (see #152).

Thoughts:
- [x] Add map to global nav (see also #151)
- [ ] (potentially) remove Timeline
- [ ] (potentially) remove Contact
- [x] discuss secondary navigation

Potential order:
` About | Map | Events | Get Involved | Contact `

**Comment by Shrinks99** [comment]
See #152

**Comment by darkdrgn2k** [comment]
see #152 for possible solution to reworking global nav

**Comment by garrying** [comment]
Updated in #172
