### ISSUE TITLE
Revisit Look and Feel

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#154]
@Shrinks99 is interested in updating branding, finalizing a logo (yay!).

Preliminary thoughts from our discussion:

- [ ] Colour palette
- [x] Distinguish footer (maybe different footer?) (possible PR #179)
- [ ] Add more graphics throughout

**Comment by dcwalk** [comment]
Just commented in #157, but thought I should also mention here -- I think it might make sense to tackle this in phases over a few PRs, sorry if this initial issue was poorly formed (aii!)

**Comment by darkdrgn2k** [comment]
Split the Hanks pr into two prs

~~Blue Color in #160  (not passing Travis??!?!)~~ Deffered
~~Logo~~ and ~~Front Page Image #159~~ Already committed logo differed

I have also added a few prs  for your consideration
~~#161 Parallax feel to the hero image on front page~~ I think its been decided no
~~#162 Keep the top nav menu at the top during scroll~~ Committed to Master

**Comment by dcwalk** [comment]
All the above PRs were reviewed at the design jam Aug 12.

@garrying, @Shrinks99 and I hashed out a consensus on the next steps:

- pull in #162 (edit: now #165) now
- cherry pick the map from #159, but leave the logo work for now
- close #160 and more that work directly to the [`look-and-feel-update`](https://github.com/tomeshnet/tomesh.net/tree/look-and-feel-update) branch. Overall progress will in the [Website Refresh milestone](https://github.com/tomeshnet/tomesh.net/milestone/1).
- close #161 until look and feel and logo work is further along.

**Comment by Shrinks99** [comment]
Closing this issue, a new website redesign will be addressed after the eventual rebrand.
