### ISSUE TITLE
Update footer to have all our contact info (github and email)

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#16]
From @garrying PR #15 ...
![screen shot 2016-05-24 at 1 35 23 pm](https://cloud.githubusercontent.com/assets/4692834/15513914/9db54b26-21b4-11e6-9cfe-63cfeda57c8a.png)

I think we should pull the email into the footer.html file so that is shown on every page!

**Comment by garrying** [comment]
Resolved in #15
