### ISSUE TITLE
Add newsletter sign up to website

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#198]
Loooong ago we set up a tinyletter as a first step as a one-way "announce" style mailing list for tomesh events and news.

Talking with @benhylau I've recently re-visited, and happy to share access (pls) to at least a few people, will shortly PR documents with details.

We should also add to the website as a signup!

cc @darkdrgn2k as I know you've mentioned one in the past!

**Comment by darkdrgn2k** [comment]
👍 Might help keep in contact with people that dont like the chat/dont check the website

Also sometimes people don't have time and and leave a project. This could be a constant reminder for them that were still around if they ever have cycles to provide back to the project :)

**Comment by darkdrgn2k** [comment]
Starte mailing list instead. 
This may convert to newsletter as time goes on

#293
