### ISSUE TITLE
Live Map Status

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/tomesh.net#211]
Outlines tasks that need to be done to add Monitoring information to the website map

- [ ] Add CJDS to server (Docker container?)
- [ ] Run Pinging script on server to generate json file
- [ ] Run Walker script on server to generate json file
  - [ ] Finish rewrite of walker script in python
- [ ] Host Prometheus Server and Grafana
- [ ] Display information on map (MapMonitoring-Links branch)

**Comment by benhylau** [comment]
Pre-req: https://github.com/tomeshnet/node-recipes/issues/1

**Comment by darkdrgn2k** [comment]
CJDNS has been removed from the network for now.
Issue closed
