### ISSUE TITLE
Improve onboard experience

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#215]
Proposing the following changes on website to give a better onboard experience:
- [x] Add a project page with links to specific Matrix chat rooms (Matrix _is_ the primary way we are using to coordinate, we should make that clear)
- [ ] Have some text that answers the questions: what is a node, can I host one? even if it's not a simple "this is a node it's 50 bucks and you can point the antenna there to get internet" that people may be hoping for
- [x] Present this Matrix community somehow so people can get a better sense of what we do: https://chat.tomesh.net/#/group/+tomesh:tomesh.net
- [x] Retire Wekan or at least don't feature it as prominently

**Comment by benhylau** [comment]
We may also want to:
- [ ] Have a page that lists public in-mesh services people run, such as Grafana dashboard, cjdns public peering, ipfs gateway, ssb pub (now these are copy and pasted across Matrix chat)
- [ ] Make visible long-form content such as https://github.com/tomeshnet/documents/tree/master/technical

**Comment by darkdrgn2k** [comment]
Larger onboarding rework ticket https://github.com/tomeshnet/toronto-community-network/issues/94

Closing ticket as it is stale
