### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/tomesh.net#222]
A new page that details the current projects the organization is working on / has completed.  

Each project is an item that can by used in some way / interacted with by somebody.  Projects are not goals or general sentiments of the organization.  "Increasing technical literacy" is not a project, "Building the Peer-to-Peer Internet Workshop, a downloadable set of materials allowing presenters to run a workshop in order increase technical literacy" is a project!

### Initial list of projects

- Mesh Orange
- Building the Peer-to-Peer Internet Workshop
- IPFS streaming
- `prototype-cjdns-pi`

### What the projects page must contain

- [ ] A short description and title of each project
- [ ] The current status of each project
- [ ] Skills currently required to help out with the project in question
- [ ] Some sort of graphic related to each project
- [ ] Link to the project in question

**Comment by benhylau** [comment]
Related https://github.com/tomeshnet/tomesh.net/issues/220
