### ISSUE TITLE
Mesh Point Interface ....... [INACTIVE]

### ISSUE THREAD

**Issue by santhoshnp** [tomeshnet/tomesh.net#233]
![screenshot 71](https://user-images.githubusercontent.com/39831264/45801232-e706c480-bcd0-11e8-9adb-8c17e81d90d5.png)

**Comment by santhoshnp** [comment]
How to activate mesh interface

**Comment by benhylau** [comment]
Wrong repository, replying on prototype repo.

**Comment by santhoshnp** [comment]
so which one is correct repository. give some solution for me and please help me

**Comment by benhylau** [comment]
I already replied you here https://github.com/tomeshnet/prototype-cjdns-pi/issues/211
The repository where you got the code from is the correct repository to file the issue.
