### ISSUE TITLE
Add a page listing mesh services

### ISSUE THREAD

**Issue by dasanchez** [tomeshnet/tomesh.net#247]
Make mesh services currently running visible on the website:

DNS at fcxx:1234 address
NTP at fcxx:7890 address

@ASoTNetworks can you tell me what else we have going? Feel free to explain how/where these services are running (anything we can use to give the page some content).

**Comment by ASoTNetworks** [comment]
Here is a list of services that I know in the mesh:

In cjdns:
- DNS:
  - fc41:47b9:dd78:ff21:1b24:dab8:3f81:168e
  - fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc
  - fc6e:691e:dfaa:b992:a10a:7b49:5a1a:5e09
  - fc16:b44c:2bf9:467:8098:51c6:5849:7b4f
- NTP:
  - fc41:47b9:dd78:ff21:1b24:dab8:3f81:168e
  - fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc
- Chat:
  - https://h.chat.tomesh.net
  - https://h.matrix.tomesh.net

In Yggdrasil:
- DNS:
  - 200:78e8:5817:319d:9cd4:cab3:93ae:6774
- NTP:
  - 200:78e8:5817:319d:9cd4:cab3:93ae:6774
- Chat:
  - https://y.chat.tomesh.net
  - https://y.matrix.tomesh.net

If anyone know other services inside the mesh that is not listed above and should be on the site please reply below.

**Comment by dasanchez** [comment]
Thanks @ASoTNetworks!
@darkdrgn2k @benhylau do you have any comments on this?

**Comment by darkdrgn2k** [comment]
# Exit Node
201:54d5:b2e9:6933:ea40:8eb6:6b8a:744
fcbb:3e34:cdfe:9e99:cb34:c3a3:1604:9955
- VPN over PIA for internet access as Exit Node

# Node1
200:857:6533:284d:dc97:62f:7562:d768  y.ssb.e-mesh.net
fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc  h.ssb.e-mesh.net

- Ntp server
- DNS server
- SSB Pub

# Node2
200:98bf:d6df:e49a:f525:40bf:18d:ac45
fc6e:691e:dfaa:b992:a10a:7b49:5a1a:5e09 h.e-mesh.net

- IPFS bootstrap
- DNS server
- NTP Server
- Promoethus Server
- Grafana Server
- WiteStar Bot
- CJDNS/Yggdrasil Map Walker and map host

# Alexandria.tomesh.net
fcef:709a:15b:de7f:eb3d:cf30:bdc0:5bfc
201:27b2:1e5d:35f1:b06d:d3b:5fff:8a10

 - Media Mirror
 - IPFS

**Comment by darkdrgn2k** [comment]
Also there are the IPFS bootstraps

https://github.com/tomeshnet/prototype-cjdns-pi/blob/320953b3283d0933ffb35aec658d43d80b9370ce/scripts/ipfs/install#L9-L19

**Comment by benhylau** [comment]
Started a page to list this on documents https://github.com/tomeshnet/documents/pull/113

**Comment by digitaldina** [comment]
Started a PR!

**Comment by benhylau** [comment]
Hey @digitaldina thanks for the email. Can you send a blank email to hello@tomesh.net so I have your email address? I want to send you the onboard email to the [Toronto Community Network](https://github.com/tomeshnet/toronto-community-network/) project. Thanks!

**Comment by darkdrgn2k** [comment]
Lots of this is out of date now with TCN starting. @digitaldina pr coveres most of the items. Closing issue
