### ISSUE TITLE
Pull important content from the documents repository to the website

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#26]
Picking up the conversation from PR #25:

> We ( @garrying and @YKCzoli ) discussed leaving meeting minutes on github as markdown is rendered nice enough and they are a bit of a deep dive into tomesh. I think we could have an **'About' and 'Contribute' page** with those details.

Thoughts?

**Comment by benhylau** [comment]
Yea have an **About and Contribute** with a link to: https://github.com/tomeshnet/documents/tree/master/meeting_notes

**Comment by dcwalk** [comment]
Hey @daynaclowe, I know you had some thoughts about website structure. Maybe there is a way for us all to set up a time to talk about it? (tho I'll be remote until end of august)

**Comment by benhylau** [comment]
We should prioritize this and put up a page or two that address **About** and **Contribute**.

**About** needs to address _what is_ and _why use_ a mesh. Much of that information has been written in various docs, they just need to be reorganized and formatted for website presentation.

**Contribute**
- [ ] Show current status (link to Wekan public read-only)
- [ ] Show where things are (how content is organized across our various Github repos)
- [ ] High-level direction and rough dates (from Planning Meeting notes)
- [ ] How to get in touch (link Vector, CivicTechTO weekly)

**Comment by dcwalk** [comment]
I agree this is a priority, but I'm not sure if all the stuff you mention belongs on the contribute (to that degree of specificity)... in particular the high-level direction & rough dates (I don't even know where those are anymore after the planning meeting. Do we have 'em?)

I think we can definitely get up a draft version and get it out once there is feedback, then iterate from there!

I'll have some cycles today and tomorrow and then none until Tuesday (but can do some offline remote work).

**Comment by dcwalk** [comment]
Hey, I wanna say we've addressed a good chunk of this:
- 'about' covers vision
- 'get involved' covers where we work and a first step to get online
- meeting minutes are linked from the event pages (which isn't super lovely, but exists)

The only thing missing is our working group leads in terms of _active info_
