### ISSUE TITLE
Onboarding for Riot - Update instructions

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/tomesh.net#260]
> Hank

looks like user onboarding for our matrix chat will be changing https://medium.com/@RiotChat/new-privacy-controls-for-riot-dc3661888563

"With the latest release you no longer select an identity server at login or registration time. Instead, you can now manage your use of an identity server in user settings"

**Comment by Shrinks99** [comment]
Hijacking this issue to also include the name change from Riot.im to Element.  Will update accordingly.

**Comment by darkdrgn2k** [comment]
@Shrinks99 closed?
