### ISSUE TITLE
Allow users to sign up for our mailing list

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/tomesh.net#293]
We have a mailing list now!  [https://lists.hypha.coop/cgi-bin/mailman/listinfo/tomeshnet](https://lists.hypha.coop/cgi-bin/mailman/listinfo/tomeshnet)

There needs to be a way to sign up for this on the homepage.

**Comment by benhylau** [comment]
@ASoTNetworks and I figured out how to make a pretty embed:

<img width="721" alt="Screen Shot 2020-08-24 at 12 48 03 PM" src="https://user-images.githubusercontent.com/2261308/91036713-1b473600-e608-11ea-9625-2eb49947894b.png">


```
<form style="line-height:1;" method="post" action="https://lists.hypha.coop/cgi-bin/mailman/subscribe/tomeshnet">
  <input style="width:100%; margin-bottom:8px;" type="email" name="email" value="" placeholder="email@example.com">
  <input style="width:100%; margin-bottom:8px;" type="text" name="fullname" value="" placeholder="Your Name (optional)">
  <input type="hidden" name="digest" value="1">
  <input style="width:30%; float:right;" type="submit" name="email-button" value="Subscribe">
</form>
```

This was on another jekyll site, but can be modified for tomesh.net.
