### ISSUE TITLE
Add navigation and content to the website

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#35]
As @garrying pointed out in PR #32 there is no way to navigate back to the proposed Event Page from an individual Event. We gotta like add some IA to this website with the expanding content. 

[edited out of date sitemap image out]

And we would need global navigation. These are pretty typical patterns for that...
<img width="784" alt="screen shot 2016-08-13 at 4 32 26 pm" src="https://cloud.githubusercontent.com/assets/4692834/17645451/7d5bdf84-6174-11e6-894c-0d76629a565a.png">

**Comment by benhylau** [comment]
I prefer **B** with single page nav like this: https://github.com/alvarotrigo/fullPage.js

**Comment by dcwalk** [comment]
I'd love a single page, but I thought website/outreach  people were overall against it, especially given the grand plans we have for content.

@garrying or @daynaclowe I trust your web design skills over mine. Thoughts on IA/navigation?

**Comment by garrying** [comment]
I'm partial to **B**. The single page nav pattern might work, but we haven't flushed out the requirements/intent of the homepage and I think there are other approaches we could look at and ideate around (maybe we can have an ideation session?). Having straight-forward content pages will seem a bit rigid to begin with, but it'll be readily visible to get feedback on for further refining/design.

**Comment by dcwalk** [comment]
@garrying yes we need to hash this out in person. Looks like right now it'll be us discussing for the first iteration (and pushing a draft for comment before finalizing implementation...?)

I've incorporated @uditvira 's comments into a draft "contribute/join us", and there is a draft "about" linked from the [wekan card](https://wekan.tomesh.net/b/LWS8X7sGFXqDgZ7ag/tomesh-net/kxfGG5wEYDJxA3fp4).

I'll ping to set up a time.

**Comment by dcwalk** [comment]
Here are some cleaned up mockups from a session with @garrying to think about website content/structure:

Please please feedback! Either here or in the [chat.tomesh.net #website room](https://chat.tomesh.net/#/room/#website:tomesh.net)

<img width="1255" alt="sitemap" src="https://cloud.githubusercontent.com/assets/4692834/18361795/5673d1a8-75d1-11e6-983a-e8268b46c995.png">
<img width="883" alt="tomesh-main" src="https://cloud.githubusercontent.com/assets/4692834/18361813/6d86201c-75d1-11e6-901d-1c3e04ea91a1.png">
<img width="882" alt="tomesh-about" src="https://cloud.githubusercontent.com/assets/4692834/18361819/7321e6fa-75d1-11e6-8542-6db0be148500.png">
<img width="885" alt="tomesh-involved" src="https://cloud.githubusercontent.com/assets/4692834/18361823/758e6670-75d1-11e6-9de3-f01e8e75b3d7.png">
<img width="885" alt="tomesh-events" src="https://cloud.githubusercontent.com/assets/4692834/18361827/78f35c1c-75d1-11e6-80da-6233881968eb.png">

**Comment by dcwalk** [comment]
Closing as this was implemented in PR #37 !
