### ISSUE TITLE
Remove announcement functionality

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.net#45]
We've removed the announcements from the homepage for now (in [this commit](https://github.com/tomeshnet/tomesh.net/pull/37/commits/e9c4e3102b804ee078d15d68c9874d9241721fed)) and intended to revisit whether we want the functionality once we launch the next version of the site.

Filing an issue so we don't lose the thread.

**Comment by garrying** [comment]
Coming back in #77

**Comment by dcwalk** [comment]
yeeee-aaah! announcements rise again :small_airplane:
