### ISSUE TITLE
Events page: Truncate upcoming events with show/hide more events

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#52]

**Comment by dcwalk** [comment]
We've decided to move forward on the site with some identified issues from events page outstanding.
(Moved from Restructure:
- [X] Cannot see more than two future **Events**, perhaps a 'More' button? 
- ~[ ] From what I remember, ~~the `ADD TO CALENDAR` button adds a static copy of all events.~~ (@dcwalk note: if you add the URL it updates) Perhaps we should have a small `+ .ics` button per event?~
- ~[ ] Maybe a one px border around each future event?)~

**Comment by dcwalk** [comment]
Ongoing todos:
- [x] use `button` and aria
- [x] change button text depending on state (open or closed)
- [x] smoother transition on toggler
