### ISSUE TITLE
Handling of events with missing "locationMap"

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#58]
For events like: https://tomesh.net/2016-11-03/virtual-mesh/

Clicking on the location link `#virtualmesh:tomesh.net` opens another tab of the page itself. I am guessing this happens when posts don't have a `locationMap` attribute. The behaviour is awkward, I think we should have it not as a link instead.

By the way, can `locationMap` be a virtual location? Or should we add another key to allow for virtual locations like: https://chat.tomesh.net/#/room/#virtualmesh:tomesh.net

**Comment by garrying** [comment]
Agreed on using virtual location. I think we can rename `locationMap` to something more general like `locationLink` and add the `chat.tomesh.net` room addresses to the entries we have so far. cc @dcwalk

**Comment by dcwalk** [comment]
Totally agree, I actually did a clean of urls & location names in this branch: 
https://github.com/tomeshnet/tomesh.net/compare/events-clean

Maybe we just switch over the `locationMap` frontmatter variable to `locationLink` and update the link on the events page for now and handle like that?

**Comment by garrying** [comment]
Yeah. Doing the switch over sounds good to me.

**Comment by dcwalk** [comment]
This is addressed in #61 and ready for review
