### ISSUE TITLE
Cannot subscribe to calendar on Android

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#59]
Clicking on the button from Chrome on Android gives error **Unable to launch event**.

**Comment by dcwalk** [comment]
I dropped some links into `#website` RE: how to look at this. I think idiom of 'click and subscribe' is wrong if we want people to add a url path to their calendaring app....

Would like a copy to clipboard a la how github allows you to clone repos make more sense? 
(and from what I can tell that would have to be js and there is cross-browser, incl. mobile, support)

**Comment by benhylau** [comment]
Are we planning to have static per event .ics in addition to this, or just have this?

**Comment by dcwalk** [comment]
We were still talking about a per event .ics and were discussing the best way to generate a per-event ics file. I think that is still on the table as a feature to implement

I've got no bandwidth for this at the moment. The website group was gonna have a standup on Mon Nov 14, not sure if it will be hashed out before then?

**Comment by benhylau** [comment]
I don't think this or per-event .ics is urgent.

**Comment by dcwalk** [comment]
Just want to circle back on this -- We can add the URL path (e.g. `https://tomesh.net/events.ics`) _as a URL_ to a calendar and it syncs.

My comments RE: JS are about copy-pasting to clipboard for someone to add that URL as an external calendar to their phone.

The other approach, a click-to-download a static version of the ICS appears like it could be addressed in sync with #136

**Comment by garrying** [comment]
This may have been resolved with a recent addition of `text/calendar ics` in `mime.types` for NGINX. I'm lacking an Android device to test with. So far it works on iOS.

**Comment by dcwalk** [comment]
Just tested on Android and I'm getting the option to download or open in calendar.
If downloading I am prompted to open it with calendaring apps as well.

**Comment by dcwalk** [comment]
To my old (old) point -- before we move to a caldev implementation do we want people to have a (somewhat) sync-able calendar?

I think the "copy this url" pattern similar like GitHub's: 
![screen shot 2017-03-28 at 5 12 20 pm](https://cloud.githubusercontent.com/assets/4692834/24427682/de1ffce8-13d9-11e7-908d-b00b78a6dd35.png)
might be the best way to accomplish that if so.

Otherwise once someone else confirms we might be good to close?

**Comment by benhylau** [comment]
If we can get a syncing calendar without caldav I'd rather not use caldev and have another piece to manage.

**Comment by Shrinks99** [comment]
Closed #142 (should have closed this a while ago! :P )
