### ISSUE TITLE
Instructions for Riot on mobile

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#69]
Use custom homeserver https://matrix.tomesh.net when using mobile clients

**Comment by dcwalk** [comment]
Good point, do you think it should go on the get involved page tho? Or should we link out to documents RE: configuration?

**Comment by benhylau** [comment]
Get Involved page along side the web instructions, because lots of people go to tomesh.net through the phone and when they click the chat.tomesh.net it tells them to download the app. They'd need to know the matrix.tomesh.net custom homeserver URL then.

**Comment by garrying** [comment]
@dcwalk Do you want to tackle this one?

**Comment by dcwalk** [comment]
👌

**Comment by dcwalk** [comment]
Resolved via #86.
