### ISSUE TITLE
Add Announcement Block

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#77]
Redesign announcements to be persistent block
  - Current idea: full-width block attached to the navigation bar, with short text and relevant link
  - Might need a different display for homepage
  - Question: Does it make sense an announcement to have a linkable page?
---
- [x] Add persistent announcement block if an announcement is present and in date range
- [x] Small viewport behaviour
- [x] Styling

**Comment by dcwalk** [comment]
Announcement looks good 👌 @slowmanchan , but can we document in the readme and or create a template like we did for events? I think we are gonna seriously need to watch announcement length 😄

**Comment by garrying** [comment]
Breaking out the documentation task to #110
