### ISSUE TITLE
Homepage: Remove the Have More Questions section

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#80]
Considerations:
- Moving Have More Questions prompt to footer
- Replace Have More Questions with Timeline link and intro paragraph to lead into Timeline

**Comment by ana0** [comment]
Today we discussed putting "build node" instructions in this block, which I have begun working on, but is open to revision

**Comment by Shrinks99** [comment]
This section was removed from the look and feel update branch as part of the homepage update

**Comment by dcwalk** [comment]
Awesome! The only thing I would say is we tend to close issues once the code is live, and I think this is still on a dev branch :)
