### ISSUE TITLE
Better Body Typography

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#82]
- Possibly introduce sub-headings (brief, medium sized paragraph) to text-only pages to help frame content
- Sourcing images for content pages (?)

**Comment by dcwalk** [comment]
I'm a little unclear: is this typography or copy structure?

RE: length. I think we are keeping it pretty trim. We only have one page that comes anywhere close to long-form and it has 2 headings on it!

Do you feel like isn't readable?

**Comment by garrying** [comment]
It was to do with both copy and typography when talked about. There are some inconsistencies with typography/layout that I'm hoping to address.

**Comment by garrying** [comment]
There isn't a solid plan for this. Closing for now.
