### ISSUE TITLE
Adding donate link/widget

### ISSUE THREAD

**Issue by garrying** [tomeshnet/tomesh.net#85]
Related to #84

**Comment by garrying** [comment]
A possible solution is using Quadriga's Merchant: https://www.quadrigacx.com/merchant_info

**Comment by benhylau** [comment]
Also looking at https://stripe.com API

**Comment by dcwalk** [comment]
What about using Librepay + a seperate Bitcoin Address? e.g. https://en.liberapay.com/matrixdotorg/

That seems like a feasible first attempt to iterate on instead of setting ourselves up on stripe?

**Comment by darkdrgn2k** [comment]
Closing due to re-structuring of project.

Open Collective ticket  at https://github.com/tomeshnet/toronto-community-network/issues/104
