### ISSUE TITLE
Downloadable .ics for events

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.net#9]
1. Generate [.ics](http://apple.stackexchange.com/a/125526) from event announcement [collection](https://jekyllrb.com/docs/collections/).
2. Show [fa-calendar-plus-o](https://fortawesome.github.io/Font-Awesome/cheatsheet/) on the announcement and link to **.ics** file.

**Comment by dcwalk** [comment]
Totally agree! 

But I think we gotta start making use of posts for upcoming events, I think the announcement can/should be unmoored from dates in a way that the calender/events would want.

Is the plan for like everything thing we do as a group (incl. civic tech nights) up?

**Comment by dcwalk** [comment]
Did a poke about, I think the [jekyll-ical gem](https://github.com/philtr/jekyll-ical) or this [gist](https://gist.github.com/woodworker/6725728) are a starting place!

**Comment by dcwalk** [comment]
Oop, this was closed by #24... shoulda caught on merge.
